services:
  # 1. Banco de Dados PostgreSQL
  database:
    image: postgres:16-alpine
    container_name: fiap_postgres
    environment:
      POSTGRES_USER: fiap_user
      POSTGRES_PASSWORD: fiap_password
      POSTGRES_DB: fiap_x_db
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fiap_user -d fiap_x_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. RabbitMQ
  rabbitmq:
    image: rabbitmq:4-management
    container_name: fiap_rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"    # Comunicação AMQP
      - "15672:15672"  # Interface Web
    environment:
      RABBITMQ_DEFAULT_USER: fiap
      RABBITMQ_DEFAULT_PASS: fiap
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

# 3. Backend Go (API)
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fiap_api
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=fiap_user
      - DB_PASSWORD=fiap_password
      - DB_NAME=fiap_x_db
      - RABBITMQ_URL=amqp://fiap:fiap@rabbitmq:5672/
    depends_on:
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    
    volumes:
      - shared_uploads:/app/uploads
      - shared_outputs:/app/outputs
      - shared_temp:/app/temp

  # 4. API Gateway (Nginx)
  gateway:
    image: nginx:alpine
    container_name: fiap_gateway
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

volumes:
  pgdata:
    driver: local
  rabbitmq_data:
    driver: local
  shared_uploads:
    driver: local
  shared_outputs:
    driver: local
  shared_temp:
    driver: local
    