events {
    worker_connections 1024;
}

http {
    # Suporte a uploads de vídeos maiores
    client_max_body_size 500M;

    server {
        # Alterado de 80 para 8080 para bater com o containerPort do K8s
        listen 8080;

        # Repassa todas as requisições para o serviço Go no Kubernetes
        location / {
            proxy_pass http://api-service:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
